# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: MATLAB Production Server Ref Arch AWS new VPC Health Check Test ap-northeast on Windows

on:
 workflow_dispatch:
 push:
 schedule:
    - cron: '0 15 * * 3'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.13
      uses: actions/setup-python@v2
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r ./healthcheck/requirements.txt
       
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: MPS Ref Arch AWS new VPC Health Check Test ap-northeast on Windows
        cd healthcheck
        export AWS_ACCESS_KEY_ID=${{ secrets.aws_access_key_id }}
        export AWS_SECRET_ACCESS_KEY=${{ secrets.aws_secret_access_key }}
        export AWS_REGION=ap-northeast-1
        python test_healthcheck_new_vnet.py ${{ secrets.KeyPairNameTokyo }} ${{ secrets.lmpassword }} ${{ secrets.ipaddress }} ${{ secrets.SSLCertificateARNTokyo }} "ap-northeast-1" "Windows"

